# Generated by Django 2.0.6 on 2018-08-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_name', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('net_bios', models.CharField(blank=True, max_length=200)),
                ('mac_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.IntegerField()),
                ('plugin_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
                ('exploit', models.CharField(max_length=50)),
                ('repository', models.CharField(max_length=200)),
                ('plugin_text', models.TextField(blank=True, max_length=500)),
                ('cve', models.CharField(blank=True, max_length=100)),
                ('first_discovered', models.DateTimeField(max_length=200)),
                ('last_observed', models.DateTimeField(max_length=200)),
                ('exploit_frameworks', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('solution', models.CharField(max_length=200)),
                ('see_also', models.URLField(blank=True)),
                ('risk_factor', models.CharField(max_length=50)),
                ('stig_severity', models.CharField(blank=True, max_length=200)),
                ('cvss_base_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('cvss_temporal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cpe', models.CharField(blank=True, max_length=100)),
                ('bid', models.BigIntegerField(blank=True)),
                ('cross_references', models.CharField(blank=True, max_length=200)),
                ('vuln_publication_date', models.CharField(max_length=200)),
                ('patch_publication_date', models.CharField(max_length=200)),
                ('plugin_publication_date', models.DateTimeField()),
                ('plugin_modification_date', models.DateTimeField()),
                ('exploit_ease', models.CharField(blank=True, max_length=200)),
                ('check_type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cve_db_app.Device')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cve_db_app.Scan')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cve_db_app.Site'),
        ),
    ]
