# Generated by Django 2.0.7 on 2018-08-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_db_app', '0002_auto_20180802_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_version',
            field=models.CharField(max_length=200),
        ),
    ]
