# Generated by Django 2.0.7 on 2018-08-09 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cve_db_app', '0003_auto_20180802_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.IntegerField()),
                ('plugin_name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
                ('exploit', models.CharField(max_length=50)),
                ('repository', models.CharField(max_length=200)),
                ('plugin_text', models.TextField(blank=True, max_length=500)),
                ('cve', models.CharField(blank=True, max_length=100)),
                ('first_discovered', models.DateTimeField(max_length=200)),
                ('last_observed', models.DateTimeField(max_length=200)),
                ('exploit_frameworks', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('solution', models.CharField(max_length=200)),
                ('see_also', models.URLField(blank=True)),
                ('risk_factor', models.CharField(max_length=50)),
                ('stig_severity', models.CharField(blank=True, max_length=200)),
                ('cvss_base_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('cvss_temporal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cpe', models.CharField(blank=True, max_length=100)),
                ('bid', models.BigIntegerField(blank=True)),
                ('cross_references', models.CharField(blank=True, max_length=200)),
                ('vuln_publication_date', models.CharField(max_length=200)),
                ('patch_publication_date', models.CharField(max_length=200)),
                ('plugin_publication_date', models.DateTimeField()),
                ('plugin_modification_date', models.DateTimeField()),
                ('exploit_ease', models.CharField(blank=True, max_length=200)),
                ('check_type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='scan_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_net_bios',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_version',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scan_results',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_name',
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='net_bios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='dns_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cve_db_app.Site'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cve_db_app.Device'),
        ),
    ]
